# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/AddPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(307, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(307, 300))
        MainWindow.setMaximumSize(QtCore.QSize(307, 300))
        MainWindow.setStyleSheet("* {\n"
"    selection-background-color: #343434;   /* Seçim arkası */\n"
"    selection-color: #e4e3e0;              /* Seçili metnin rengi */\n"
"}\n"
"\n"
"#centralwidget{\n"
"background-color: #343434\n"
"}\n"
"QPushButton{\n"
"color: #343434;\n"
"background-color: #e4e3e0;\n"
"border-radius: 20px;   /* Yuvarlamayı artır */\n"
"}\n"
"QLabel{\n"
"color:#e4e3e0;\n"
"}\n"
"QLineEdit{\n"
"color: #e4e3e0;\n"
"background-color: #343434;\n"
"selection-background-color: #e4e3e0;   /* Seçim arkası */\n"
"selection-color: #343434;              /* Seçili metnin rengi */\n"
"}\n"
"QSpinBox{\n"
"    background-color: #343434;\n"
"    color: #e4e3e0;\n"
"    selection-background-color: #e4e3e0;\n"
"    selection-color: #343434;\n"
"}\n"
"\n"
"QMessageBox QLabel{\n"
"color: #000000\n"
"}\n"
"QMessageBox QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"    padding: 4px 12px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(110, 27))
        self.label_15.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(110, 27))
        self.label_14.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(110, 27))
        self.label_12.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(110, 27))
        self.label_13.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.lineEdit_plakaEkle = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_plakaEkle.sizePolicy().hasHeightForWidth())
        self.lineEdit_plakaEkle.setSizePolicy(sizePolicy)
        self.lineEdit_plakaEkle.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEdit_plakaEkle.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_plakaEkle.setFont(font)
        self.lineEdit_plakaEkle.setText("")
        self.lineEdit_plakaEkle.setObjectName("lineEdit_plakaEkle")
        self.gridLayout_2.addWidget(self.lineEdit_plakaEkle, 0, 1, 1, 1)
        self.lineEdit_markaEkle = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_markaEkle.sizePolicy().hasHeightForWidth())
        self.lineEdit_markaEkle.setSizePolicy(sizePolicy)
        self.lineEdit_markaEkle.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEdit_markaEkle.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_markaEkle.setFont(font)
        self.lineEdit_markaEkle.setText("")
        self.lineEdit_markaEkle.setObjectName("lineEdit_markaEkle")
        self.gridLayout_2.addWidget(self.lineEdit_markaEkle, 1, 1, 1, 1)
        self.lineEdit_modelEkle = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_modelEkle.sizePolicy().hasHeightForWidth())
        self.lineEdit_modelEkle.setSizePolicy(sizePolicy)
        self.lineEdit_modelEkle.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEdit_modelEkle.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_modelEkle.setFont(font)
        self.lineEdit_modelEkle.setText("")
        self.lineEdit_modelEkle.setObjectName("lineEdit_modelEkle")
        self.gridLayout_2.addWidget(self.lineEdit_modelEkle, 2, 1, 1, 1)
        self.spinBox_gunlukUcretEkle = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_gunlukUcretEkle.sizePolicy().hasHeightForWidth())
        self.spinBox_gunlukUcretEkle.setSizePolicy(sizePolicy)
        self.spinBox_gunlukUcretEkle.setMinimumSize(QtCore.QSize(171, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_gunlukUcretEkle.setFont(font)
        self.spinBox_gunlukUcretEkle.setMaximum(100000)
        self.spinBox_gunlukUcretEkle.setSingleStep(100)
        self.spinBox_gunlukUcretEkle.setObjectName("spinBox_gunlukUcretEkle")
        self.gridLayout_2.addWidget(self.spinBox_gunlukUcretEkle, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_ekle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ekle.sizePolicy().hasHeightForWidth())
        self.pushButton_ekle.setSizePolicy(sizePolicy)
        self.pushButton_ekle.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ekle.setFont(font)
        self.pushButton_ekle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_ekle.setObjectName("pushButton_ekle")
        self.verticalLayout.addWidget(self.pushButton_ekle)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Page"))
        self.label_16.setText(_translate("MainWindow", "Araç Ekle"))
        self.label_15.setText(_translate("MainWindow", "Model:"))
        self.label_14.setText(_translate("MainWindow", "Günlük Ücret:"))
        self.label_12.setText(_translate("MainWindow", "Marka:"))
        self.label_13.setText(_translate("MainWindow", "Plaka:"))
        self.pushButton_ekle.setText(_translate("MainWindow", "Ekle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
