# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/EditPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(307, 316)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(307, 316))
        MainWindow.setMaximumSize(QtCore.QSize(307, 316))
        MainWindow.setStyleSheet("* {\n"
"    selection-background-color: #343434;   /* Seçim arkası */\n"
"    selection-color: #e4e3e0;              /* Seçili metnin rengi */\n"
"}\n"
"\n"
"#centralwidget{\n"
"background-color: #343434\n"
"}\n"
"QPushButton{\n"
"color: #343434;\n"
"background-color: #e4e3e0;\n"
"border-radius: 20px;   /* Yuvarlamayı artır */\n"
"}\n"
"QLabel{\n"
"color:#e4e3e0;\n"
"}\n"
"QLineEdit{\n"
"color: #e4e3e0;\n"
"background-color: #343434;\n"
"selection-background-color: #e4e3e0;   /* Seçim arkası */\n"
"selection-color: #343434;              /* Seçili metnin rengi */\n"
"}\n"
"QSpinBox{\n"
"    background-color: #343434;\n"
"    color: #e4e3e0;\n"
"    selection-background-color: #e4e3e0;\n"
"    selection-color: #343434;\n"
"}\n"
"\n"
"#lineEdit_plakaDuzenle{\n"
"    selection-background-color: #343434;\n"
"    selection-color: #e4e3e0;\n"
"}\n"
"\n"
"QMessageBox QLabel{\n"
"color: #000000\n"
"}\n"
"QMessageBox QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"    padding: 4px 12px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit_plakaDuzenle = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_plakaDuzenle.sizePolicy().hasHeightForWidth())
        self.lineEdit_plakaDuzenle.setSizePolicy(sizePolicy)
        self.lineEdit_plakaDuzenle.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEdit_plakaDuzenle.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_plakaDuzenle.setFont(font)
        self.lineEdit_plakaDuzenle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_plakaDuzenle.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_plakaDuzenle.setReadOnly(True)
        self.lineEdit_plakaDuzenle.setObjectName("lineEdit_plakaDuzenle")
        self.verticalLayout.addWidget(self.lineEdit_plakaDuzenle)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(110, 27))
        self.label_15.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(110, 27))
        self.label_12.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(110, 27))
        self.label_14.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.lineEdit_modelDuzenle = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_modelDuzenle.sizePolicy().hasHeightForWidth())
        self.lineEdit_modelDuzenle.setSizePolicy(sizePolicy)
        self.lineEdit_modelDuzenle.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEdit_modelDuzenle.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_modelDuzenle.setFont(font)
        self.lineEdit_modelDuzenle.setText("")
        self.lineEdit_modelDuzenle.setObjectName("lineEdit_modelDuzenle")
        self.gridLayout_2.addWidget(self.lineEdit_modelDuzenle, 2, 1, 1, 1)
        self.lineEdit_markaDuzenle = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_markaDuzenle.sizePolicy().hasHeightForWidth())
        self.lineEdit_markaDuzenle.setSizePolicy(sizePolicy)
        self.lineEdit_markaDuzenle.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEdit_markaDuzenle.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_markaDuzenle.setFont(font)
        self.lineEdit_markaDuzenle.setText("")
        self.lineEdit_markaDuzenle.setObjectName("lineEdit_markaDuzenle")
        self.gridLayout_2.addWidget(self.lineEdit_markaDuzenle, 1, 1, 1, 1)
        self.spinBox_gunlukUcretDuzenle = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_gunlukUcretDuzenle.sizePolicy().hasHeightForWidth())
        self.spinBox_gunlukUcretDuzenle.setSizePolicy(sizePolicy)
        self.spinBox_gunlukUcretDuzenle.setMinimumSize(QtCore.QSize(171, 27))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_gunlukUcretDuzenle.setFont(font)
        self.spinBox_gunlukUcretDuzenle.setMaximum(100000)
        self.spinBox_gunlukUcretDuzenle.setSingleStep(100)
        self.spinBox_gunlukUcretDuzenle.setObjectName("spinBox_gunlukUcretDuzenle")
        self.gridLayout_2.addWidget(self.spinBox_gunlukUcretDuzenle, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_duzenle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_duzenle.sizePolicy().hasHeightForWidth())
        self.pushButton_duzenle.setSizePolicy(sizePolicy)
        self.pushButton_duzenle.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_duzenle.setFont(font)
        self.pushButton_duzenle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_duzenle.setObjectName("pushButton_duzenle")
        self.verticalLayout.addWidget(self.pushButton_duzenle)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Edit Page"))
        self.label_16.setText(_translate("MainWindow", "Araç Düzenle"))
        self.lineEdit_plakaDuzenle.setText(_translate("MainWindow", "34 ABC 53"))
        self.label_15.setText(_translate("MainWindow", "Model:"))
        self.label_12.setText(_translate("MainWindow", "Marka:"))
        self.label_14.setText(_translate("MainWindow", "Günlük Ücret:"))
        self.pushButton_duzenle.setText(_translate("MainWindow", "Düzenle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
