# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(402, 290))
        MainWindow.setMaximumSize(QtCore.QSize(402, 290))
        MainWindow.setStyleSheet("#centralwidget{\n"
"background-color: #e4e3e0\n"
"}\n"
"QPushButton{\n"
"color: #f4f3f0;\n"
"background-color: #343434;\n"
"border-radius: 15px;   /* Yuvarlamayı artır */\n"
"}\n"
"QLabel{\n"
"color:#343434\n"
"}\n"
"/*209d9d turkuaz yeşili*/")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_admin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_admin.setGeometry(QtCore.QRect(220, 130, 131, 91))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_admin.setFont(font)
        self.pushButton_admin.setObjectName("pushButton_admin")
        self.pushButton_kullanici = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kullanici.setGeometry(QtCore.QRect(50, 130, 131, 91))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_kullanici.setFont(font)
        self.pushButton_kullanici.setObjectName("pushButton_kullanici")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login Page"))
        self.pushButton_admin.setText(_translate("MainWindow", "Admin Girişi"))
        self.pushButton_kullanici.setText(_translate("MainWindow", "Kullanıcı Girişi"))
        self.label.setText(_translate("MainWindow", "CARENTO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
