# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/RentPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 405)
        MainWindow.setMinimumSize(QtCore.QSize(310, 405))
        MainWindow.setMaximumSize(QtCore.QSize(310, 405))
        MainWindow.setStyleSheet("* {\n"
"    selection-background-color: #343434;   /* Seçim arkası */\n"
"    selection-color: #e4e3e0;              /* Seçili metnin rengi */\n"
"}\n"
"\n"
"#centralwidget{\n"
"background-color: #343434\n"
"}\n"
"QPushButton{\n"
"color: #343434;\n"
"background-color: #e4e3e0;\n"
"border-radius: 20px;   /* Yuvarlamayı artır */\n"
"}\n"
"QLabel{\n"
"color:#e4e3e0;\n"
"}\n"
"QLineEdit{\n"
"color: #e4e3e0;\n"
"background-color: #343434;\n"
"selection-background-color: #343434;   /* Seçim arkası */\n"
"selection-color: #e4e3e0;              /* Seçili metnin rengi */\n"
"}\n"
"QSpinBox{\n"
"    background-color: #343434;\n"
"    color: #e4e3e0;\n"
"    selection-background-color: #e4e3e0;\n"
"    selection-color: #343434;\n"
"}\n"
"\n"
"#lineEdit_adKirala{\n"
"    selection-background-color: #e4e3e0;\n"
"    selection-color: #343434;\n"
"}\n"
"\n"
"QMessageBox QLabel{\n"
"color: #000000\n"
"}\n"
"QMessageBox QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"    padding: 4px 12px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit_plakaKirala = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_plakaKirala.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_plakaKirala.sizePolicy().hasHeightForWidth())
        self.lineEdit_plakaKirala.setSizePolicy(sizePolicy)
        self.lineEdit_plakaKirala.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEdit_plakaKirala.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_plakaKirala.setFont(font)
        self.lineEdit_plakaKirala.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_plakaKirala.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_plakaKirala.setReadOnly(True)
        self.lineEdit_plakaKirala.setObjectName("lineEdit_plakaKirala")
        self.verticalLayout.addWidget(self.lineEdit_plakaKirala)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, 2, -1, 30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_markaKirala = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_markaKirala.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_markaKirala.sizePolicy().hasHeightForWidth())
        self.lineEdit_markaKirala.setSizePolicy(sizePolicy)
        self.lineEdit_markaKirala.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEdit_markaKirala.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_markaKirala.setFont(font)
        self.lineEdit_markaKirala.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_markaKirala.setReadOnly(True)
        self.lineEdit_markaKirala.setObjectName("lineEdit_markaKirala")
        self.horizontalLayout.addWidget(self.lineEdit_markaKirala)
        self.lineEdit_modelKirala = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_modelKirala.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_modelKirala.sizePolicy().hasHeightForWidth())
        self.lineEdit_modelKirala.setSizePolicy(sizePolicy)
        self.lineEdit_modelKirala.setMinimumSize(QtCore.QSize(100, 27))
        self.lineEdit_modelKirala.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_modelKirala.setFont(font)
        self.lineEdit_modelKirala.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_modelKirala.setReadOnly(True)
        self.lineEdit_modelKirala.setObjectName("lineEdit_modelKirala")
        self.horizontalLayout.addWidget(self.lineEdit_modelKirala)
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(80, 27))
        self.label_19.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(80, 27))
        self.label_6.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.dateEdit_baslangicKirala = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_baslangicKirala.setFont(font)
        self.dateEdit_baslangicKirala.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(3000, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateEdit_baslangicKirala.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_baslangicKirala.setObjectName("dateEdit_baslangicKirala")
        self.gridLayout.addWidget(self.dateEdit_baslangicKirala, 1, 1, 1, 1)
        self.dateEdit_bitisKirala = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_bitisKirala.setFont(font)
        self.dateEdit_bitisKirala.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(3000, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateEdit_bitisKirala.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2025, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_bitisKirala.setObjectName("dateEdit_bitisKirala")
        self.gridLayout.addWidget(self.dateEdit_bitisKirala, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(80, 27))
        self.label_20.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 0, 1, 1)
        self.lineEdit_adKirala = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_adKirala.sizePolicy().hasHeightForWidth())
        self.lineEdit_adKirala.setSizePolicy(sizePolicy)
        self.lineEdit_adKirala.setMinimumSize(QtCore.QSize(171, 27))
        self.lineEdit_adKirala.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_adKirala.setFont(font)
        self.lineEdit_adKirala.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_adKirala.setText("")
        self.lineEdit_adKirala.setObjectName("lineEdit_adKirala")
        self.gridLayout.addWidget(self.lineEdit_adKirala, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.lineEdit_toplamUcretKirala = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_toplamUcretKirala.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_toplamUcretKirala.sizePolicy().hasHeightForWidth())
        self.lineEdit_toplamUcretKirala.setSizePolicy(sizePolicy)
        self.lineEdit_toplamUcretKirala.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEdit_toplamUcretKirala.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_toplamUcretKirala.setFont(font)
        self.lineEdit_toplamUcretKirala.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_toplamUcretKirala.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_toplamUcretKirala.setReadOnly(True)
        self.lineEdit_toplamUcretKirala.setObjectName("lineEdit_toplamUcretKirala")
        self.verticalLayout.addWidget(self.lineEdit_toplamUcretKirala)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_kirala = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_kirala.sizePolicy().hasHeightForWidth())
        self.pushButton_kirala.setSizePolicy(sizePolicy)
        self.pushButton_kirala.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_kirala.setFont(font)
        self.pushButton_kirala.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_kirala.setObjectName("pushButton_kirala")
        self.verticalLayout.addWidget(self.pushButton_kirala)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rent Page"))
        self.label_11.setText(_translate("MainWindow", "Araç Kirala"))
        self.lineEdit_plakaKirala.setText(_translate("MainWindow", "34 ABC 53"))
        self.lineEdit_markaKirala.setText(_translate("MainWindow", "AUDI"))
        self.lineEdit_modelKirala.setText(_translate("MainWindow", "A4"))
        self.label_19.setText(_translate("MainWindow", "Başlangıç:"))
        self.label_6.setText(_translate("MainWindow", "Ad Soyad:"))
        self.label_20.setText(_translate("MainWindow", "Bitiş:"))
        self.lineEdit_toplamUcretKirala.setText(_translate("MainWindow", "12400 TL"))
        self.pushButton_kirala.setText(_translate("MainWindow", "Kirala"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
