# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/UserPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        MainWindow.setStyleSheet("* {\n"
"    selection-background-color: #343434;   /* Seçim arkası */\n"
"    selection-color: #e4e3e0;              /* Seçili metnin rengi */\n"
"}\n"
"#MainWindow{\n"
"background-color: #343434\n"
"}\n"
"#centralwidget{\n"
"background-color: #343434\n"
"}\n"
"#dockWidget{\n"
"color: #e4e3e0;\n"
"background-color: #545454\n"
"}\n"
"#dockWidgetContents{\n"
"background-color: #343434\n"
"}\n"
"QLabel{\n"
"color: #e4e3e0\n"
"}\n"
"QMessageBox QLabel{\n"
"color: #000000\n"
"}\n"
"QMessageBox QPushButton {\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"    padding: 4px 12px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"color: #e4e3e0;\n"
"background-color: #343434;\n"
"selection-background-color: #e4e3e0;   /* Seçim arkası */\n"
"selection-color: #343434;              /* Seçili metnin rengi */\n"
"}\n"
"QDateEdit {\n"
"    color: #e4e3e0;\n"
"    background-color: #343434;\n"
"    selection-background-color: #e4e3e0;\n"
"    selection-color: #343434;\n"
"}\n"
"QSpinBox{\n"
"    background-color: #343434;\n"
"    color: #e4e3e0;\n"
"    selection-background-color: #e4e3e0;\n"
"    selection-color: #343434;\n"
"}\n"
"QComboBox {\n"
"    color: #343434;\n"
"    background-color: #e4e3e0;\n"
"}\n"
"QPushButton{\n"
"background-color: #e4e3e0;\n"
"color: #343434;\n"
"border-radius: 15px;   /* Yuvarlamayı artır */\n"
"}\n"
"#pushButton_filtrele{\n"
"border-radius: 5px;   /* Yuvarlamayı artır */\n"
"}\n"
"\n"
"/* Tablo arka planı */\n"
"QTableWidget {\n"
"    background-color: #2E2E2E;\n"
"    color: #e4e3e0;\n"
"    gridline-color: #555;\n"
"    selection-background-color: #4C8BF5;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: #343434;   /* boş kalan tüm alan */\n"
"}\n"
"QTableCornerButton::section {\n"
"    background-color: #343434;   /* sol üst köşedeki buton */\n"
"}\n"
"\n"
"/* Sütun başlıkları */\n"
"QHeaderView::section {\n"
"    background-color: #444444;\n"
"    color: #e4e3e0;\n"
"    padding: 4px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Hücrelerin arka planı */\n"
"QTableWidget::item {\n"
"    background-color: #2E2E2E;\n"
"    color: #e4e3e0;\n"
"}\n"
"\n"
"/* Seçilen cell */\n"
"QTableWidget::item:selected {\n"
"    background-color: #e4e3e0;\n"
"    color: #343434;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(600, 50))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_filtrele = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_filtrele.sizePolicy().hasHeightForWidth())
        self.pushButton_filtrele.setSizePolicy(sizePolicy)
        self.pushButton_filtrele.setMinimumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_filtrele.setFont(font)
        self.pushButton_filtrele.setStyleSheet("")
        self.pushButton_filtrele.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../assets/images/filterIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_filtrele.setIcon(icon)
        self.pushButton_filtrele.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_filtrele.setObjectName("pushButton_filtrele")
        self.horizontalLayout_3.addWidget(self.pushButton_filtrele)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.tableWidget_aracListesi = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_aracListesi.sizePolicy().hasHeightForWidth())
        self.tableWidget_aracListesi.setSizePolicy(sizePolicy)
        self.tableWidget_aracListesi.setMinimumSize(QtCore.QSize(620, 400))
        self.tableWidget_aracListesi.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_aracListesi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_aracListesi.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_aracListesi.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_aracListesi.setTabKeyNavigation(False)
        self.tableWidget_aracListesi.setProperty("showDropIndicator", False)
        self.tableWidget_aracListesi.setDragDropOverwriteMode(False)
        self.tableWidget_aracListesi.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_aracListesi.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_aracListesi.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_aracListesi.setObjectName("tableWidget_aracListesi")
        self.tableWidget_aracListesi.setColumnCount(5)
        self.tableWidget_aracListesi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_aracListesi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_aracListesi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_aracListesi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_aracListesi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_aracListesi.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget_aracListesi)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_kirala = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_kirala.sizePolicy().hasHeightForWidth())
        self.pushButton_kirala.setSizePolicy(sizePolicy)
        self.pushButton_kirala.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_kirala.setFont(font)
        self.pushButton_kirala.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_kirala.setObjectName("pushButton_kirala")
        self.horizontalLayout_2.addWidget(self.pushButton_kirala)
        self.pushButton_iadeEt = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_iadeEt.sizePolicy().hasHeightForWidth())
        self.pushButton_iadeEt.setSizePolicy(sizePolicy)
        self.pushButton_iadeEt.setMinimumSize(QtCore.QSize(300, 60))
        self.pushButton_iadeEt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_iadeEt.setFont(font)
        self.pushButton_iadeEt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_iadeEt.setObjectName("pushButton_iadeEt")
        self.horizontalLayout_2.addWidget(self.pushButton_iadeEt)
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(250, 400))
        self.dockWidget.setMaximumSize(QtCore.QSize(250, 40000))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_markaFiltrele = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_markaFiltrele.setGeometry(QtCore.QRect(90, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_markaFiltrele.setFont(font)
        self.lineEdit_markaFiltrele.setObjectName("lineEdit_markaFiltrele")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_modelFiltrele = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_modelFiltrele.setGeometry(QtCore.QRect(90, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_modelFiltrele.setFont(font)
        self.lineEdit_modelFiltrele.setObjectName("lineEdit_modelFiltrele")
        self.lineEdit_minFiyat = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_minFiyat.setGeometry(QtCore.QRect(10, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_minFiyat.setFont(font)
        self.lineEdit_minFiyat.setObjectName("lineEdit_minFiyat")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(0, 140, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(110, 180, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_maxFiyat = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_maxFiyat.setGeometry(QtCore.QRect(140, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_maxFiyat.setFont(font)
        self.lineEdit_maxFiyat.setObjectName("lineEdit_maxFiyat")
        self.comboBox_kiraDurumuFiltrele = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox_kiraDurumuFiltrele.setGeometry(QtCore.QRect(30, 300, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_kiraDurumuFiltrele.setFont(font)
        self.comboBox_kiraDurumuFiltrele.setObjectName("comboBox_kiraDurumuFiltrele")
        self.comboBox_kiraDurumuFiltrele.addItem("")
        self.comboBox_kiraDurumuFiltrele.addItem("")
        self.comboBox_kiraDurumuFiltrele.addItem("")
        self.label_18 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_18.setGeometry(QtCore.QRect(0, 260, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.pushButton_filtreUygula = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_filtreUygula.setGeometry(QtCore.QRect(50, 380, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_filtreUygula.setFont(font)
        self.pushButton_filtreUygula.setObjectName("pushButton_filtreUygula")
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setGeometry(QtCore.QRect(240, 0, 21, 2000))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Page"))
        self.label.setText(_translate("MainWindow", "Araç Listesi            "))
        item = self.tableWidget_aracListesi.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Plaka"))
        item = self.tableWidget_aracListesi.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Marka"))
        item = self.tableWidget_aracListesi.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Model"))
        item = self.tableWidget_aracListesi.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Günlük Ücret"))
        item = self.tableWidget_aracListesi.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Kira Durumu"))
        self.pushButton_kirala.setText(_translate("MainWindow", "Kirala"))
        self.pushButton_iadeEt.setText(_translate("MainWindow", "İade Et"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Filtrele"))
        self.label_2.setText(_translate("MainWindow", "Marka:"))
        self.label_3.setText(_translate("MainWindow", "Model:"))
        self.label_4.setText(_translate("MainWindow", "Fiyat Aralığı"))
        self.label_5.setText(_translate("MainWindow", "-"))
        self.comboBox_kiraDurumuFiltrele.setItemText(0, _translate("MainWindow", "Tümü"))
        self.comboBox_kiraDurumuFiltrele.setItemText(1, _translate("MainWindow", "Müsait olanları göster"))
        self.comboBox_kiraDurumuFiltrele.setItemText(2, _translate("MainWindow", "Kirada olanları göster"))
        self.label_18.setText(_translate("MainWindow", "Kira Durumu"))
        self.pushButton_filtreUygula.setText(_translate("MainWindow", "Filtreleri Uygula"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
